name = "playground"
version = "0.0.1"
description = "Embedded Code runner in web pages, supports multiple programming languages."
documentation = "https://github.com/amphitheatre-app/playground"
repository = "https://github.com/amphitheatre-app/playground"
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["javascript", "editor", "playground", "typescript", "embedded", "frontend", "webapp", "code-runner"]
categories = ["editor", "ide", "develop-tools"]

[build]
dockerfile = "Dockerfile"

[deploy.env]
API_ENDPOINT = "http://playground-api:8080"

[partners]
playground-api = { repo = "https://github.com/amphitheatre-app/playground-api" }
