version: '3'

services:
  playground-api:
    image: ghcr.io/amphitheatre-app/playground-api:latest
    ports:
    - 8080:8080
    environment:
      AMP_PORT: 8080
      AMP_SERVER: http://localhost:8170

  playground:
    image: ghcr.io/amphitheatre-app/playground:v0.0.1
    ports:
    - 3000:3000
    environment:
      PORT: 3000
